apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartlearnai-llmops-aiops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smartlearnai-llmops-aiops
  template:
    metadata:
      labels:
        app: smartlearnai-llmops-aiops
    spec:
      containers:
      - name: smartlearnai-llmops-aiops
        image: andrewdoss77/smartlearn_ai:__IMAGE_TAG__
        ports:
        - containerPort: 8501
        env:
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: groq-api-secret
              key: GROQ_API_KEY
